### ISSUE TITLE
I want to download a song 

### ISSUE THREAD

**Issue by anirudhanishal** [sachinsenal0x64/hifi-tui#10]
### Which tool

I want to download a song how it's possible from
https://tidal.401658.xyz/track/?id=348010945&quality=LOSSLESS

### Describe your question

I want to download a song how it's possible from
https://tidal.401658.xyz/track/?id=348010945&quality=LOSSLESS

### Add screenshots

I want to download a song how it's possible from
https://tidal.401658.xyz/track/?id=348010945&quality=LOSSLESS

**Comment by sachinsenal0x64** [comment]
![Image](https://github.com/sachinsenal0x64/hifi-tui/assets/127573781/82e1c056-3771-4290-bf59-69eb7201a8f7)

use this https://github.com/yt-dlp/yt-dlp

example = yt-dlp "Original Track URL”

**Comment by anirudhanishal** [comment]
https://tidal.401658.xyz/track/?id=348010945&quality=LOSSLESS
In this url can I Show orginal lossless file url

**Comment by sachinsenal0x64** [comment]
This ![image](https://github.com/sachinsenal0x64/hifi-tui/assets/127573781/2c5803ea-5965-438a-9966-191fdfb74727)

**Comment by anirudhanishal** [comment]
Check once the url is not correct
