### ISSUE TITLE
Can I download file with album cover

### ISSUE THREAD

**Issue by anirudhanishal** [sachinsenal0x64/hifi-tui#11]
### Which tool

Can I download file with album cover

### Describe your question

Can I download file with album cover

### Add screenshots

Can I download file with album cover

**Comment by sachinsenal0x64** [comment]
Any example URL ?

**Comment by anirudhanishal** [comment]
No that's not I need when I download original track it's download with cover when I play on music player it's showing with song name and cover

**Comment by sachinsenal0x64** [comment]
Use this https://github.com/yaronzz/Tidal-Media-Downloader
