### ISSUE TITLE
Original track url not working to play or stream 

### ISSUE THREAD

**Issue by anirudhanishal** [sachinsenal0x64/hifi-tui#12]
### Which tool

Original track url not working to play or stream 

### Describe your question

Original track url not working to play or stream 

### Add screenshots

Original track url not working to play or stream

**Comment by sachinsenal0x64** [comment]
Just working.

![image](https://github.com/sachinsenal0x64/hifi-tui/assets/127573781/a21ff9b3-f32b-44a2-8148-a28e9292a751)

**Comment by sachinsenal0x64** [comment]
if you have any question feel free to ask cheers 🍺

**Comment by anirudhanishal** [comment]
Now working

**Comment by anirudhanishal** [comment]
One question site is very slow to fetch data

**Comment by sachinsenal0x64** [comment]
> One question site is very slow to fetch data Any issues

Probably a JSON issue. I will try to optimize it.

**Comment by anirudhanishal** [comment]
Ok
