### ISSUE TITLE
Track not found please solved

### ISSUE THREAD

**Issue by anirudhanishal** [sachinsenal0x64/hifi-tui#17]
### Which tool

https://tidal.401658.xyz/track/?id=266874640&quality=LOSSLESS

### Describe your question

https://tidal.401658.xyz/track/?id=266874640&quality=LOSSLESS

### Add screenshots

https://tidal.401658.xyz/track/?id=266874640&quality=LOSSLESS
Track not found url error 
All track url error

**Comment by sachinsenal0x64** [comment]
Fixed!

**Comment by anirudhanishal** [comment]
Thank you
