### ISSUE TITLE
how do i use dolby atmos quality and also how do I download the atmos quality also and also does this work with ytdlp and also how do i find specific albums

### ISSUE THREAD

**Issue by Pickymarker** [sachinsenal0x64/hifi-tui#18]
### Which tool

how do i use dolby atmos quality and also how do I download the atmos quality also and also does this work with ytdlp and also how do i find specific playlist like this https://tidal.com/playlist/af989059-3068-4477-9e19-f279ffa4f8c2 as a example of a atmos playlist

### Describe your question

how do i use dolby atmos quality and also how do I download the atmos quality also and also does this work with ytdlp and also how do i find specific playlist like this https://tidal.com/playlist/af989059-3068-4477-9e19-f279ffa4f8c2 as a example of a atmos playlist

**Comment by sachinsenal0x64** [comment]
Dolby Atmos is already embedded within the track; you can find it in the metadata section.

Playlist = https://tidal.401658.xyz/playlist/?id=af989059-3068-4477-9e19-f279ffa4f8c2

Track = https://tidal.401658.xyz/track/?id=296654139&quality=LOSSLESS

For more, read the docs = https://github.com/sachinsenal0x64/hifi-tui?tab=readme-ov-file#-api-documentation


![image](https://github.com/sachinsenal0x64/hifi-tui/assets/127573781/9d6c36fa-8b0d-410f-9ae8-95ec08acf2f0)

![image](https://github.com/sachinsenal0x64/hifi-tui/assets/127573781/07b9f736-6fff-4335-9203-c34ba460d96d)

**Comment by Pickymarker** [comment]
why does audio file still show 2 channel when it should show around 6.1 and also how do you do sony 360 songs

**Comment by sachinsenal0x64** [comment]
Sony360 = https://tidal.401658.xyz/album/?id=157117504

**Comment by Pickymarker** [comment]
> Note:
> 
> ![image](https://private-user-images.githubusercontent.com/127573781/326261685-f2f60daa-3184-4c67-8dba-08ed4899a9b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQwOTEsIm5iZiI6MTcxNDMxMzc5MSwicGF0aCI6Ii8xMjc1NzM3ODEvMzI2MjYxNjg1LWYyZjYwZGFhLTMxODQtNGM2Ny04ZGJhLTA4ZWQ0ODk5YTliOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNDE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjdjMWQxNTc2OWE5MzQ0Y2FjNTQxNWE0YTk2ZDVkNmM1NDM4YTg2YjQ5MTIyOGZkY2RjMTAyZWNlZGRlZDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bjTlr4Pi7ovEwidoDuZ6Xf1CaHiUKSPTRAV3VHM5Nb4)
> 
> Sony360 = https://tidal.401658.xyz/album/?id=157117504
> 
> Track = https://tidal.401658.xyz/track/?id=157117505&quality=LOSSLESS
> 
> ![image](https://private-user-images.githubusercontent.com/127573781/326261612-95889b3c-b0bf-4002-90e2-364945708f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQwOTEsIm5iZiI6MTcxNDMxMzc5MSwicGF0aCI6Ii8xMjc1NzM3ODEvMzI2MjYxNjEyLTk1ODg5YjNjLWIwYmYtNDAwMi05MGUyLTM2NDk0NTcwOGY3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNDE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjJlODNhOTg3M2UwNjI4NDVkYjQ4OGRlMmM4MzNhYjQ5ZTA2ODVmNWYyODBmMDE1MDY2YjYyZTZjNTM3ODY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3JFxTSKq-2aWfWXYm1rS40HIZ9nnfOQpsFekrg4byCw)

then why do other tidal downloaders support surround

**Comment by sachinsenal0x64** [comment]
If stereo tracks like LOSSLESS or Hi_RES feel more “surround”

**Comment by sachinsenal0x64** [comment]
> > Note:
> > ![image](https://private-user-images.githubusercontent.com/127573781/326261685-f2f60daa-3184-4c67-8dba-08ed4899a9b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQwOTEsIm5iZiI6MTcxNDMxMzc5MSwicGF0aCI6Ii8xMjc1NzM3ODEvMzI2MjYxNjg1LWYyZjYwZGFhLTMxODQtNGM2Ny04ZGJhLTA4ZWQ0ODk5YTliOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNDE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjdjMWQxNTc2OWE5MzQ0Y2FjNTQxNWE0YTk2ZDVkNmM1NDM4YTg2YjQ5MTIyOGZkY2RjMTAyZWNlZGRlZDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bjTlr4Pi7ovEwidoDuZ6Xf1CaHiUKSPTRAV3VHM5Nb4)
> > Sony360 = https://tidal.401658.xyz/album/?id=157117504
> > Track = https://tidal.401658.xyz/track/?id=157117505&quality=LOSSLESS
> > ![image](https://private-user-images.githubusercontent.com/127573781/326261612-95889b3c-b0bf-4002-90e2-364945708f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQwOTEsIm5iZiI6MTcxNDMxMzc5MSwicGF0aCI6Ii8xMjc1NzM3ODEvMzI2MjYxNjEyLTk1ODg5YjNjLWIwYmYtNDAwMi05MGUyLTM2NDk0NTcwOGY3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNDE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjJlODNhOTg3M2UwNjI4NDVkYjQ4OGRlMmM4MzNhYjQ5ZTA2ODVmNWYyODBmMDE1MDY2YjYyZTZjNTM3ODY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3JFxTSKq-2aWfWXYm1rS40HIZ9nnfOQpsFekrg4byCw)
> 
> then why do other tidal downloaders support surround

If Tidal has 5.1 / 6.1 surround sound, then the HIFI API will return.

**Comment by sachinsenal0x64** [comment]
Anyway, I will add surround sound/stereo/mono options to the HIFI TUI in a future release.
