### ISSUE TITLE
how do you use on windows 

### ISSUE THREAD

**Issue by Pickymarker** [sachinsenal0x64/Hifi-Tui#4]
how do you use on windows

**Comment by sachinsenal0x64** [comment]
You mean API or TUI

**Comment by sachinsenal0x64** [comment]
TUI still work in progress, But Free API you can use (https://tidal.401658.xyz/track/?id=123456&quality=LOSSLESS). Get the track ID (also called song ID) from Tidal and replace it. Btw, I will add music search function asp. :)
