### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Fibey** [sachinsenal0x64/Hifi-Tui#5]
HIFI and HIFI_RES qualities are not working but HI_RES is working which is not mentioned in the README file

examples:

HI_RES: https://tidal.401658.xyz/track/?id=76888641&quality=HI_RES

HIFI_RES: https://tidal.401658.xyz/track/?id=76888641&quality=HIFI_RES

HIFI: https://tidal.401658.xyz/track/?id=76888641&quality=HIFI

**Comment by sachinsenal0x64** [comment]
Thank you for remembering it should HI_RES :)
